# Generated by Django 5.1.5 on 2025-01-27 14:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0008_remove_product_subcategory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='available_from',
        ),
        migrations.RemoveField(
            model_name='category',
            name='available_to',
        ),
        migrations.AlterField(
            model_name='category',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='menu.category'),
        ),
    ]
